---
abstract: 'Easily use Email::Sender from Dancer'
author:
  - 'Michael Alan Dorman <mdorman@ironicdesign.com>'
build_requires:
  Email::Sender::Transport::Test: 0
  Email::Simple: 0
  IO::File: 0
  Sub::Exporter: 0
  Test::Compile: 0
  Test::Fatal: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-EmailSender
requires:
  Carp: 0
  Dancer: 0
  Dancer::Plugin: 0
  Email::MIME: 0
  Email::Sender::Simple: 0
  Module::Load: 0
  Scalar::Util: 0
  Test::More: 0
  strict: 0
  warnings: 0
version: 0.002
